const VERTALINGEN = {
  nl: {
    // Hoofdscherm — header
    'header.mapImporteren': '↑ Map importeren',
    'header.youtubeZoeken': '⌕ YouTube zoeken',
    'header.jukebox': '♫ Jukebox',
    'header.help': '? Help',
    'header.prullenbakLabel': 'Sleep hierheen om te verwijderen',
    'header.themaKiezen': 'Kies een thema',
    'header.taalKiezen': 'Kies een taal',

    // Tabs
    'tabs.walls': 'Mijn walls',
    'tabs.concerten': 'Mijn concerten',

    // Thema's
    'thema.standaard': 'Standaard',
    'thema.metaal': 'Metaal',
    'thema.jukebox': 'Jukebox',
    'thema.nacht': 'Nacht',
    'thema.raw': 'Raw',
    'thema.natuur': 'Natuur',
    'thema.licht': 'Licht',

    // Selectie / jukebox-toevoegen
    'selectie.voegToeAanPlaylist': '♫ Voeg toe aan de playlist',
    'selectie.tekst': '{n} geselecteerd · Esc om te deselecteren',
    'jukebox.geenSelectie': 'Selecteer eerst videos met Ctrl+klik.',

    // Walls
    'wall.nummerToevoegen': '+ nummer toevoegen',
    'wall.nieuweWall': 'Nieuwe wall',
    'wall.hernoemenTooltip': 'Klik om te hernoemen',
    'wall.verwijderenTooltip': 'Wall verwijderen',
    'wall.selecteerAllesTooltip': 'Selecteer/deselecteer alle video\'s in deze wall',
    'wall.toonAlle': 'Toon nog {n} video\'s',
    'wall.verwijderen.titel': 'Wall verwijderen',
    'wall.verwijderen.bevestiging': 'Weet u zeker dat u "{naam}" wilt verwijderen?',
    'wall.verwijderen.metVideos': 'Dit verwijdert ook {n} video(s) in deze wall.',
    'wall.verwijderen.leeg': 'Deze wall is leeg.',
    'wallGroep.nieuweGroepTooltip': 'Nieuwe groep',
    'wallGroep.verwijderenTooltip': 'Groep verwijderen',
    'wallGroep.hernoemenTooltip': 'Dubbelklik om te hernoemen',
    'wallGroep.selectLabel': 'Groep',
    'wallGroep.geenWalls': 'Geen walls in deze groep',
    'wallGroep.verwijderen.titel': 'Groep verwijderen',
    'wallGroep.verwijderen.bevestiging': 'Weet u zeker dat u de groep "{naam}" wilt verwijderen? De walls erin blijven bestaan, maar worden niet meer gegroepeerd.',

    // Video's
    'video.bron.youtube': 'YouTube',
    'video.bron.lokaal': 'Lokaal',
    'video.verwijderenTooltip': 'Video verwijderen',
    'video.bewerkenTooltip': 'Video bewerken',
    'video.verwijderen.titel': 'Video verwijderen',
    'video.verwijderen.bevestiging': 'Weet u zeker dat u "{naam}" wilt verwijderen?',
    'video.meerdereVerwijderen.titel': '{n} videos verwijderen',
    'video.meerdereVerwijderen.bevestiging': 'Weet u zeker dat u {n} video(s) wilt verwijderen?',

    // Concerten
    'concert.nieuw': 'Nieuw concert',
    'concert.leeg': 'Nog geen concertervaringen — klik op + om uw eerste concert toe te voegen.',
    'concert.items': '{n} items',
    'concert.verwijderenTooltip': 'Concert verwijderen',
    'concert.bewerkenTooltip': 'Concert bewerken',
    'concert.verwijderen.titel': 'Concert verwijderen',
    'concert.verwijderen.bevestiging': 'Weet u zeker dat u "{naam}" wilt verwijderen?',
    'concert.verwijderen.metMedia': 'Dit verwijdert ook {n} foto/video item(s) in dit concert.',
    'concert.verwijderen.geenMedia': 'Dit concert heeft nog geen media.',

    // Concert-detail
    'concertDetail.fotoVideoToevoegen': '📁 Foto / video toevoegen',
    'concertDetail.youtubeToevoegen': '▶ YouTube toevoegen',
    'concertDetail.geenMedia': 'Nog geen foto\'s of video\'s toegevoegd.',
    'concertDetail.verwijderenTooltip': 'Item verwijderen',
    'concertDetail.mediaFilterNaam': 'Foto en video',
    'concertDetail.selecteerAllesBtn': '☑ Selecteer alles',

    // Nieuw concert / concert bewerken
    'nieuwConcert.titel': 'Nieuw concert',
    'nieuwConcert.bewerkenTitel': 'Concert bewerken',
    'nieuwConcert.naamLabel': 'Naam van het concert',
    'nieuwConcert.naamPlaceholder': 'bijv. Elements of Life Tour',
    'nieuwConcert.artiestLabel': 'Artiest',
    'nieuwConcert.artiestPlaceholder': 'bijv. Tiësto',
    'nieuwConcert.datumLabel': 'Datum',
    'nieuwConcert.datumPlaceholder': 'bijv. 14 maart 2018',
    'nieuwConcert.verhaalLabel': 'Verhaal',
    'nieuwConcert.verhaalPlaceholder': 'Wat maakte deze avond bijzonder?',
    'nieuwConcert.aanmakenBtn': 'Concert aanmaken',

    // Nummer toevoegen
    'toevoegen.titel': 'Nummer toevoegen',
    'toevoegen.typeYoutube': 'YouTube',
    'toevoegen.typeLokaal': 'Lokaal bestand',
    'toevoegen.youtubeUrlLabel': 'YouTube URL',
    'toevoegen.videobestandLabel': 'Videobestand',
    'toevoegen.kiesBestandBtn': '📁 Kies bestand',
    'toevoegen.geenBestandGekozen': 'Geen bestand gekozen',
    'toevoegen.artiestLabel': 'Artiest',
    'toevoegen.artiestPlaceholder': 'Naam van de artiest',
    'toevoegen.titelLabel': 'Titel',
    'toevoegen.titelPlaceholder': 'Naam van het nummer',
    'toevoegen.verhaalLabel': 'Verhaal',
    'toevoegen.verhaalPlaceholder': 'Waarom betekent dit nummer iets voor u?',
    'toevoegen.tagLabel': 'Tag',
    'toevoegen.tagPlaceholder': 'bijv. Live · Concert of Omwenteling',

    // Nummer bewerken
    'bewerken.titel': 'Nummer bewerken',

    // Nieuwe wall / wall hernoemen
    'nieuweWall.titel': 'Nieuwe wall',
    'nieuweWall.hernoemenTitel': 'Wall hernoemen',
    'nieuweWall.naamLabel': 'Naam van de wall',
    'nieuweWall.naamPlaceholder': 'bijv. Live Concerten',
    'nieuweWall.aanmakenBtn': 'Aanmaken',
    'nieuweWallGroep.titel': 'Nieuwe groep',
    'nieuweWallGroep.hernoemenTitel': 'Groep hernoemen',
    'nieuweWallGroep.naamLabel': 'Naam van de groep',
    'nieuweWallGroep.naamPlaceholder': 'bijv. Feestjes',
    'nieuweWallGroep.aanmakenBtn': 'Aanmaken',
    'hernoemTab.titel': 'Tab hernoemen',
    'hernoemTab.naamLabel': 'Naam van de tab',

    // Videos importeren
    'importeren.titel': 'Videos importeren',
    'importeren.wallLabel': 'Wall',
    'importeren.kiesMapBtn': 'Kies map',
    'importeren.importerenBtn': 'Importeren',
    'importeren.videobestandenGevonden': '{n} videobestanden gevonden',
    'importeren.voortgang': '{i} van {n} — {naam}',
    'importeren.klaar': 'Klaar — {n} videos geïmporteerd',
    'importeren.voltooid': '✓ Import voltooid',
    'importeren.geenVideosTitel': 'Geen videos gevonden',
    'importeren.geenVideosBericht': 'Er zijn geen videobestanden gevonden in deze map.',
    'importeren.mapKiezenTitel': 'Kies een map met videos',

    // YouTube zoeken
    'zoeken.titel': 'YouTube zoeken',
    'zoeken.zoektermPlaceholder': 'Zoek een nummer of artiest...',
    'zoeken.zoekenBtn': 'Zoeken',
    'zoeken.toevoegenAanWall': 'Toevoegen aan wall',
    'zoeken.voegGeselecteerdeToe': '♫ Voeg geselecteerde toe',
    'zoeken.zoeken': 'Zoeken...',
    'zoeken.geenResultaten': 'Geen resultaten gevonden.',
    'zoeken.fout': 'Fout: {bericht}',
    'zoeken.misgegaan': 'Er ging iets mis: {bericht}',
    'zoeken.toegevoegd': '✓ Toegevoegd',
    'zoeken.apiKeyOntbreekt': 'Open het bestand: {pad}<br><br>Vul daar uw eigen YouTube API-sleutel in om te kunnen zoeken.',
    'zoeken.instellingenFout': 'Kon de instellingen niet laden: {bericht}',
    'zoeken.videoFilterNaam': 'Video',
    'zoeken.modusVideos': 'Video\'s',
    'zoeken.modusPlaylists': 'Playlists',
    'zoeken.playlistZoektermPlaceholder': 'Zoek een playlist op artiest of genre...',
    'zoeken.geenPlaylists': 'Geen playlists gevonden.',
    'zoeken.terugNaarPlaylists': '← Terug naar playlists',
    'zoeken.selecteerAlles': 'Selecteer alles',

    // Jukebox
    'jukebox.playlist': 'Playlist',
    'jukebox.leegmaken': 'Leegmaken',
    'jukebox.bibliotheekZoeken': 'Zoek in je bibliotheek...',
    'jukebox.herkomstWall': 'Wall: {naam}',
    'jukebox.herkomstConcert': 'Concert: {naam}',
    'jukebox.kiesNummer': 'Kies een nummer uit de playlist',
    'jukebox.schermvullend': 'Schermvullend',
    'jukebox.shuffle': 'Shuffle',
    'jukebox.eerste': 'Eerste',
    'jukebox.vorige': 'Vorige',
    'jukebox.afspelen': 'Afspelen',
    'jukebox.stoppen': 'Stoppen',
    'jukebox.volgende': 'Volgende',
    'jukebox.laatste': 'Laatste',
    'jukebox.leegLijst': 'Selecteer videos in een wall en klik op "Voeg toe aan de playlist".',
    'jukebox.alleAfgespeeld': 'Alle nummers zijn afgespeeld',
    'jukebox.eindeLijst': 'Einde van de playlist',
    'jukebox.nietAfspeelbaar': '"{titel}" niet afspeelbaar, verwijderd uit de playlist (handmatig nog wel mogelijk)',

    // Bevestigen dialoog
    'bevestigen.annuleren': 'Annuleren',
    'bevestigen.verwijderen': 'Verwijderen',

    // Algemeen / validatie
    'algemeen.opslaanBtn': 'Opslaan',
    'algemeen.opgeslagen': '✓ Opgeslagen',
    'validatie.vulNaamIn': 'Vul een naam in.',
    'validatie.vulTitelIn': 'Vul minimaal een titel in.',
    'validatie.vulYoutubeUrlIn': 'Vul een YouTube URL in.',
    'validatie.kiesVideobestand': 'Kies een videobestand.',
    'validatie.geenWall': 'Geen wall geselecteerd.',

    // Help
    'help.titel': 'Help',
    'help.versieLabel': 'Versie {versie}',
    'help.walls.titel': 'Walls',
    'help.walls.intro': 'Een wall is een muur met video\'s rond een thema — bijvoorbeeld concerten, omwentelingen, of momenten met vrienden.',
    'help.walls.li1': 'Klik op de <strong>+</strong> rechts naast de walls om een nieuwe wall aan te maken',
    'help.walls.li2': 'Klik op de naam van een wall om hem te hernoemen',
    'help.walls.li3': 'Klik op het prullenbak-icoon in een wall-header om de hele wall te verwijderen, inclusief alle video\'s erin',
    'help.walls.li4': 'Sleep een video naar een andere wall om hem te verplaatsen',
    'help.walls.li5': 'Sleep een video omhoog of omlaag binnen dezelfde wall om de volgorde aan te passen — de nieuwe volgorde wordt automatisch opgeslagen',
    'help.walls.li6': 'Houd <strong>Ctrl</strong> ingedrukt en klik op meerdere video\'s om ze samen te selecteren en te verslepen',
    'help.walls.li7': 'Sleep een wall aan de kop naar een andere positie om de volgorde van de walls te wijzigen — de nieuwe volgorde wordt automatisch opgeslagen',
    'help.tabs.titel': 'Tabs & wall-groepen',
    'help.tabs.intro': 'Naast de vaste tabs "Mijn walls" en "Mijn concerten" kunt u eigen groepstabs aanmaken om walls in te verdelen, bijvoorbeeld per thema of gelegenheid.',
    'help.tabs.li1': 'Klik op de <strong>+</strong>-tab helemaal rechts om een nieuwe groep aan te maken',
    'help.tabs.li2': 'Sleep een wall aan de kop naar een groepstab om hem aan die groep toe te wijzen; sleep hem naar "Mijn walls" om de groepering weer op te heffen',
    'help.tabs.li3': 'Een nieuwe wall die u aanmaakt terwijl een groepstab actief is, komt automatisch in die groep terecht',
    'help.tabs.li4': 'Dubbelklik op een tab (ook "Mijn walls" en "Mijn concerten") om hem te hernoemen',
    'help.tabs.li5': 'Beweeg over een groepstab en klik op &times; om de groep te verwijderen; de walls erin blijven bestaan, maar worden ongegroepeerd',
    'help.tabs.li6': 'Sleep groepstabs onderling om hun volgorde te wijzigen',
    'help.concerten.titel': 'Concertervaringen',
    'help.concerten.intro': 'Een concertervaring bundelt foto\'s en video\'s van één concert, met een verhaal en datum erbij.',
    'help.concerten.li1': 'Klik op <strong>+ Nieuw concert</strong> om een concertervaring aan te maken',
    'help.concerten.li2': 'Klik op een concertkaart om de foto\'s en video\'s te bekijken en toe te voegen',
    'help.concerten.li3': '✎ — wijzig naam, artiest, datum en verhaal; 🗑 — verwijder het concert, met bevestiging',
    'help.concerten.li4': 'Sleep een concertkaart naar een andere positie om de volgorde aan te passen — de nieuwe volgorde wordt automatisch opgeslagen',
    'help.concerten.li5': 'Klik op een foto of video om te bladeren met ‹ › (of de pijltjestoetsen) door alle media van het concert; een video speelt pas af nadat u op de afspeelknop klikt',
    'help.toevoegen.titel': 'Video\'s toevoegen',
    'help.toevoegen.li1': '<strong>+ nummer toevoegen</strong> onderaan een wall — voeg een YouTube link of lokaal bestand toe, samen met artiest, titel, verhaal en tag',
    'help.toevoegen.li2': '<strong>↑ Map importeren</strong> — voeg een hele map met lokale videobestanden in één keer toe aan een wall',
    'help.toevoegen.li3': '<strong>⌕ YouTube zoeken</strong> — zoek direct binnen Musicwall naar YouTube video\'s, selecteer er één of meerdere met een klik en voeg ze in één keer toe aan de gekozen wall',
    'help.toevoegen.liPlaylists': 'Kies bovenaan het YouTube zoeken-scherm voor <strong>Playlists</strong> om te zoeken op een hele afspeellijst van een artiest of genre; selecteer een playlist om alle nummers erin te zien, gebruik <strong>Selecteer alles</strong> om ze in één keer te selecteren en voeg ze toe aan de gekozen wall',
    'help.toevoegen.li4': 'Bij Map importeren en YouTube zoeken kiest u eerst een groep, daarna een wall uit die groep — zo blijft de lijst overzichtelijk als u wall-groepen gebruikt',
    'help.afspelen.titel': 'Video\'s afspelen',
    'help.afspelen.intro': 'Klik op een thumbnail om de video af te spelen. De video opent schermvullend in een eigen venster, zonder de YouTube-interface eromheen.',
    'help.afspelen.li1': 'Druk op <strong>Escape</strong> om het videovenster te sluiten',
    'help.afspelen.li2': 'Beweeg over een thumbnail om de afspeelknop en de bewerk/verwijder knoppen te zien',
    'help.afspelen.li3': 'Een rood label toont YouTube, een goudkleurig label toont een lokale video',
    'help.bewerken.titel': 'Video\'s bewerken en verwijderen',
    'help.bewerken.li1': '✎ — bewerk artiest, titel, verhaal en tag',
    'help.bewerken.li2': '🗑 — verwijder een video, met bevestiging',
    'help.bewerken.li3': 'Sleep een video naar de prullenbak in de header om hem te verwijderen',
    'help.bewerken.li4': 'Selecteer meerdere video\'s met <strong>Ctrl+klik</strong> en sleep ze samen naar de prullenbak, of verwijder ze in één keer',
    'help.jukebox.titel': 'Jukebox',
    'help.jukebox.intro': 'De jukebox speelt een playlist van lokale én YouTube-video\'s automatisch achter elkaar af. Voor YouTube-nummers is een internetverbinding nodig; een nummer dat niet afgespeeld kan worden (bijvoorbeeld omdat de uploader insluiten heeft uitgeschakeld) wordt uit de playlist verwijderd — de video zelf blijft gewoon bestaan en is handmatig af te spelen, alleen niet via de jukebox.',
    'help.jukebox.li1': 'Selecteer video\'s met <strong>Ctrl+klik</strong> in een wall of concertervaring — lokale bestanden én YouTube-video\'s',
    'help.jukebox.liAlles': 'Klik op het selecteer-icoon in een wall-header (of de knop <strong>☑ Selecteer alles</strong> in een concertervaring) om in één keer alle video\'s van die wall of dat concert te selecteren; klik nogmaals om ze te deselecteren',
    'help.jukebox.li2': 'Klik op <strong>♫ Voeg toe aan de playlist</strong>',
    'help.jukebox.li3': 'Open de jukebox via de <strong>♫ Jukebox</strong> knop in de header',
    'help.jukebox.liBibliotheekZoeken': 'In de jukebox zelf kun je ook boven de playlist direct in je hele bibliotheek zoeken op artiest of titel — klik gevonden nummers aan (of gebruik <strong>Selecteer alles</strong>) en klik op <strong>♫ Voeg toe aan de playlist</strong> om ze toe te voegen zonder de jukebox te sluiten',
    'help.jukebox.li4': 'Gebruik de navigatieknoppen om te bladeren: eerste, vorige, afspelen/pauzeren, stoppen, volgende, laatste. Handmatig bladeren verwijdert niets uit de playlist',
    'help.jukebox.li5': 'De schudknop (⤮) husselt de volgorde van de playlist',
    'help.jukebox.li6': 'Klik op het schermvullend-icoon rechtsonder in het videoscherm voor volledig scherm',
    'help.jukebox.li7': 'Een video die vanzelf is uitgespeeld, wordt automatisch uit de playlist verwijderd; daarna gaat het afspelen verder met het volgende nummer, of terug naar het eerste als het laatste nummer was',
    'help.jukebox.li8': 'Wanneer de playlist leeg is verschijnt een melding',
    'help.jukebox.liBeperking': 'Sommige officiële muziekvideo\'s (vaak van platenlabels) hebben insluiten uitgeschakeld — dit is een instelling van de rechthebbende zelf op YouTube en kan Musicwall niet omzeilen. Dit komt vaker voor bij lijsten met veel officiële videoclips, bijvoorbeeld een Top 2000-playlist; zulke nummers zijn dan alleen handmatig af te spelen, niet via de jukebox',
    'help.apikey.titel': 'YouTube zoeken instellen',
    'help.apikey.intro': 'Om YouTube te kunnen doorzoeken vanuit Musicwall heeft u een gratis YouTube API-key nodig. Bij de eerste opstart verschijnt hiervoor automatisch een scherm met uitleg en een link naar Google; onderstaande stappen kunt u ook gebruiken om dit later alsnog in te stellen.',
    'help.apikey.aanvragenTitel': 'API-key aanvragen',
    'help.apikey.li1': 'Ga naar <strong>console.cloud.google.com</strong> en log in met een Google-account',
    'help.apikey.li2': 'Maak een nieuw project aan via <strong>Project selecteren → Nieuw project</strong>',
    'help.apikey.li3': 'Ga naar <strong>API\'s en services → Bibliotheek</strong>',
    'help.apikey.li4': 'Zoek op <strong>YouTube Data API v3</strong> en klik op <strong>Inschakelen</strong>',
    'help.apikey.li5': 'Ga naar <strong>API\'s en services → Inloggegevens</strong>',
    'help.apikey.li6': 'Klik op <strong>Inloggegevens maken → API-sleutel</strong>',
    'help.apikey.li7': 'Kopieer de sleutel die verschijnt',
    'help.apikey.invoerenTitel': 'API-key invoeren in Musicwall',
    'help.apikey.invoerLi1': 'Open het bestand <strong>instellingen.json</strong> in uw Musicwall-map',
    'help.apikey.invoerLi2': 'Vul uw sleutel in bij <strong>youtubeApiKey</strong>',
    'help.apikey.invoerLi3': 'Sla het bestand op en herstart Musicwall',
    'help.apikey.quota': 'De gratis quota van Google staat 10.000 zoekopdrachten per dag toe — meer dan genoeg voor persoonlijk gebruik.',
    'help.apikey.wijzigBtn': '🔑 API-sleutel wijzigen',
    'apiSleutelDialoog.titel': 'YouTube API-sleutel instellen',
    'apiSleutelDialoog.titelWijzigen': 'YouTube API-sleutel wijzigen',
    'apiSleutelDialoog.intro': 'Om video\'s op YouTube te kunnen zoeken heeft Musicwall een gratis YouTube API-sleutel nodig. Vraag deze eenmalig aan via Google en plak hem hieronder — dit scherm verschijnt niet meer zodra dat gelukt is.',
    'apiSleutelDialoog.introWijzigen': 'Pas hier uw YouTube API-sleutel aan.',
    'apiSleutelDialoog.openGoogleBtn': '🔗 Open Google Cloud Console',
    'apiSleutelDialoog.sleutelLabel': 'YouTube API-sleutel',
    'apiSleutelDialoog.sleutelPlaceholder': 'Plak hier uw API-sleutel',
    'apiSleutelDialoog.opslaanBtn': 'Opslaan',
    'apiSleutelDialoog.overslaanBtn': 'Later instellen',
    'apiSleutelDialoog.annulerenBtn': 'Annuleren',
    'apiSleutelDialoog.leegMelding': 'Vul een API-sleutel in, of kies "Later instellen"',
    'help.themas.titel': 'Thema\'s',
    'help.themas.intro': 'Wissel via de knop rechtsboven tussen zeven beschikbare thema\'s: Standaard, Metaal, Jukebox, Nacht, Raw, Natuur en Licht. De keuze wordt onthouden voor de volgende keer dat u Musicwall opent.',
    'help.sneltoetsen.titel': 'Sneltoetsen',
    'help.sneltoetsen.li1': '<strong>Ctrl + klik</strong> — video selecteren voor verslepen, verwijderen, of toevoegen aan de jukebox',
    'help.sneltoetsen.li2': '<strong>Escape</strong> — selectie opheffen, of videovenster sluiten'
  },

  en: {
    'header.mapImporteren': '↑ Import folder',
    'header.youtubeZoeken': '⌕ Search YouTube',
    'header.jukebox': '♫ Jukebox',
    'header.help': '? Help',
    'header.prullenbakLabel': 'Drag here to delete',
    'header.themaKiezen': 'Choose a theme',
    'header.taalKiezen': 'Choose a language',

    'tabs.walls': 'My walls',
    'tabs.concerten': 'My concerts',

    'thema.standaard': 'Default',
    'thema.metaal': 'Metal',
    'thema.jukebox': 'Jukebox',
    'thema.nacht': 'Night',
    'thema.raw': 'Raw',
    'thema.natuur': 'Nature',
    'thema.licht': 'Light',

    'selectie.voegToeAanPlaylist': '♫ Add to playlist',
    'selectie.tekst': '{n} selected · Esc to deselect',
    'jukebox.geenSelectie': 'First select videos with Ctrl+click.',

    'wall.nummerToevoegen': '+ add track',
    'wall.nieuweWall': 'New wall',
    'wall.hernoemenTooltip': 'Click to rename',
    'wall.verwijderenTooltip': 'Delete wall',
    'wall.selecteerAllesTooltip': 'Select/deselect all videos in this wall',
    'wall.toonAlle': 'Show {n} more videos',
    'wall.verwijderen.titel': 'Delete wall',
    'wall.verwijderen.bevestiging': 'Are you sure you want to delete "{naam}"?',
    'wall.verwijderen.metVideos': 'This will also delete {n} video(s) in this wall.',
    'wall.verwijderen.leeg': 'This wall is empty.',
    'wallGroep.nieuweGroepTooltip': 'New group',
    'wallGroep.verwijderenTooltip': 'Delete group',
    'wallGroep.hernoemenTooltip': 'Double-click to rename',
    'wallGroep.selectLabel': 'Group',
    'wallGroep.geenWalls': 'No walls in this group',
    'wallGroep.verwijderen.titel': 'Delete group',
    'wallGroep.verwijderen.bevestiging': 'Are you sure you want to delete the group "{naam}"? The walls in it will remain, just ungrouped.',

    'video.bron.youtube': 'YouTube',
    'video.bron.lokaal': 'Local',
    'video.verwijderenTooltip': 'Delete video',
    'video.bewerkenTooltip': 'Edit video',
    'video.verwijderen.titel': 'Delete video',
    'video.verwijderen.bevestiging': 'Are you sure you want to delete "{naam}"?',
    'video.meerdereVerwijderen.titel': 'Delete {n} videos',
    'video.meerdereVerwijderen.bevestiging': 'Are you sure you want to delete {n} video(s)?',

    'concert.nieuw': 'New concert',
    'concert.leeg': 'No concert experiences yet — click + to add your first concert.',
    'concert.items': '{n} items',
    'concert.verwijderenTooltip': 'Delete concert',
    'concert.bewerkenTooltip': 'Edit concert',
    'concert.verwijderen.titel': 'Delete concert',
    'concert.verwijderen.bevestiging': 'Are you sure you want to delete "{naam}"?',
    'concert.verwijderen.metMedia': 'This will also delete {n} photo/video item(s) in this concert.',
    'concert.verwijderen.geenMedia': 'This concert has no media yet.',

    'concertDetail.fotoVideoToevoegen': '📁 Add photo / video',
    'concertDetail.youtubeToevoegen': '▶ Add YouTube',
    'concertDetail.geenMedia': 'No photos or videos added yet.',
    'concertDetail.verwijderenTooltip': 'Delete item',
    'concertDetail.mediaFilterNaam': 'Photo and video',
    'concertDetail.selecteerAllesBtn': '☑ Select all',

    'nieuwConcert.titel': 'New concert',
    'nieuwConcert.bewerkenTitel': 'Edit concert',
    'nieuwConcert.naamLabel': 'Concert name',
    'nieuwConcert.naamPlaceholder': 'e.g. Elements of Life Tour',
    'nieuwConcert.artiestLabel': 'Artist',
    'nieuwConcert.artiestPlaceholder': 'e.g. Tiësto',
    'nieuwConcert.datumLabel': 'Date',
    'nieuwConcert.datumPlaceholder': 'e.g. March 14, 2018',
    'nieuwConcert.verhaalLabel': 'Story',
    'nieuwConcert.verhaalPlaceholder': 'What made this evening special?',
    'nieuwConcert.aanmakenBtn': 'Create concert',

    'toevoegen.titel': 'Add track',
    'toevoegen.typeYoutube': 'YouTube',
    'toevoegen.typeLokaal': 'Local file',
    'toevoegen.youtubeUrlLabel': 'YouTube URL',
    'toevoegen.videobestandLabel': 'Video file',
    'toevoegen.kiesBestandBtn': '📁 Choose file',
    'toevoegen.geenBestandGekozen': 'No file chosen',
    'toevoegen.artiestLabel': 'Artist',
    'toevoegen.artiestPlaceholder': 'Artist name',
    'toevoegen.titelLabel': 'Title',
    'toevoegen.titelPlaceholder': 'Track name',
    'toevoegen.verhaalLabel': 'Story',
    'toevoegen.verhaalPlaceholder': 'Why does this track mean something to you?',
    'toevoegen.tagLabel': 'Tag',
    'toevoegen.tagPlaceholder': 'e.g. Live · Concert or Turning point',

    'bewerken.titel': 'Edit track',

    'nieuweWall.titel': 'New wall',
    'nieuweWall.hernoemenTitel': 'Rename wall',
    'nieuweWall.naamLabel': 'Wall name',
    'nieuweWall.naamPlaceholder': 'e.g. Live Concerts',
    'nieuweWall.aanmakenBtn': 'Create',
    'nieuweWallGroep.titel': 'New group',
    'nieuweWallGroep.hernoemenTitel': 'Rename group',
    'nieuweWallGroep.naamLabel': 'Group name',
    'nieuweWallGroep.naamPlaceholder': 'e.g. Parties',
    'nieuweWallGroep.aanmakenBtn': 'Create',
    'hernoemTab.titel': 'Rename tab',
    'hernoemTab.naamLabel': 'Tab name',

    'importeren.titel': 'Import videos',
    'importeren.wallLabel': 'Wall',
    'importeren.kiesMapBtn': 'Choose folder',
    'importeren.importerenBtn': 'Import',
    'importeren.videobestandenGevonden': '{n} video files found',
    'importeren.voortgang': '{i} of {n} — {naam}',
    'importeren.klaar': 'Done — {n} videos imported',
    'importeren.voltooid': '✓ Import complete',
    'importeren.geenVideosTitel': 'No videos found',
    'importeren.geenVideosBericht': 'No video files were found in this folder.',
    'importeren.mapKiezenTitel': 'Choose a folder with videos',

    'zoeken.titel': 'Search YouTube',
    'zoeken.zoektermPlaceholder': 'Search a track or artist...',
    'zoeken.zoekenBtn': 'Search',
    'zoeken.toevoegenAanWall': 'Add to wall',
    'zoeken.voegGeselecteerdeToe': '♫ Add selected',
    'zoeken.zoeken': 'Searching...',
    'zoeken.geenResultaten': 'No results found.',
    'zoeken.fout': 'Error: {bericht}',
    'zoeken.misgegaan': 'Something went wrong: {bericht}',
    'zoeken.toegevoegd': '✓ Added',
    'zoeken.apiKeyOntbreekt': 'Open the file: {pad}<br><br>Enter your own YouTube API key there to be able to search.',
    'zoeken.instellingenFout': 'Could not load settings: {bericht}',
    'zoeken.videoFilterNaam': 'Video',
    'zoeken.modusVideos': 'Videos',
    'zoeken.modusPlaylists': 'Playlists',
    'zoeken.playlistZoektermPlaceholder': 'Search a playlist by artist or genre...',
    'zoeken.geenPlaylists': 'No playlists found.',
    'zoeken.terugNaarPlaylists': '← Back to playlists',
    'zoeken.selecteerAlles': 'Select all',

    'jukebox.playlist': 'Playlist',
    'jukebox.leegmaken': 'Clear',
    'jukebox.bibliotheekZoeken': 'Search your library...',
    'jukebox.herkomstWall': 'Wall: {naam}',
    'jukebox.herkomstConcert': 'Concert: {naam}',
    'jukebox.kiesNummer': 'Choose a track from the playlist',
    'jukebox.schermvullend': 'Fullscreen',
    'jukebox.shuffle': 'Shuffle',
    'jukebox.eerste': 'First',
    'jukebox.vorige': 'Previous',
    'jukebox.afspelen': 'Play',
    'jukebox.stoppen': 'Stop',
    'jukebox.volgende': 'Next',
    'jukebox.laatste': 'Last',
    'jukebox.leegLijst': 'Select videos in a wall and click "Add to playlist".',
    'jukebox.alleAfgespeeld': 'All tracks have been played',
    'jukebox.eindeLijst': 'End of playlist',
    'jukebox.nietAfspeelbaar': '"{titel}" not playable, removed from playlist (still playable manually)',

    'bevestigen.annuleren': 'Cancel',
    'bevestigen.verwijderen': 'Delete',

    'algemeen.opslaanBtn': 'Save',
    'algemeen.opgeslagen': '✓ Saved',
    'validatie.vulNaamIn': 'Please enter a name.',
    'validatie.vulTitelIn': 'Please enter at least a title.',
    'validatie.vulYoutubeUrlIn': 'Please enter a YouTube URL.',
    'validatie.kiesVideobestand': 'Please choose a video file.',
    'validatie.geenWall': 'No wall selected.',

    'help.titel': 'Help',
    'help.versieLabel': 'Version {versie}',
    'help.walls.titel': 'Walls',
    'help.walls.intro': 'A wall is a collection of videos around a theme — for example concerts, milestones, or moments with friends.',
    'help.walls.li1': 'Click the <strong>+</strong> next to the walls to create a new wall',
    'help.walls.li2': 'Click a wall\'s name to rename it',
    'help.walls.li3': 'Click the trash icon in a wall header to delete the whole wall, including all its videos',
    'help.walls.li4': 'Drag a video to another wall to move it',
    'help.walls.li5': 'Drag a video up or down within the same wall to reorder it — the new order is saved automatically',
    'help.walls.li6': 'Hold <strong>Ctrl</strong> and click multiple videos to select and drag them together',
    'help.walls.li7': 'Drag a wall by its header to another position to change the order of the walls — the new order is saved automatically',
    'help.tabs.titel': 'Tabs & wall groups',
    'help.tabs.intro': 'Besides the fixed "My walls" and "My concerts" tabs, you can create your own group tabs to organize walls, for example by theme or occasion.',
    'help.tabs.li1': 'Click the <strong>+</strong> tab at the far right to create a new group',
    'help.tabs.li2': 'Drag a wall by its header onto a group tab to assign it to that group; drag it onto "My walls" to remove it from the group again',
    'help.tabs.li3': 'A new wall you create while a group tab is active is automatically added to that group',
    'help.tabs.li4': 'Double-click a tab (including "My walls" and "My concerts") to rename it',
    'help.tabs.li5': 'Hover over a group tab and click &times; to delete the group; the walls in it remain, just ungrouped',
    'help.tabs.li6': 'Drag group tabs among themselves to change their order',
    'help.concerten.titel': 'Concert experiences',
    'help.concerten.intro': 'A concert experience bundles photos and videos from one concert, together with a story and date.',
    'help.concerten.li1': 'Click <strong>+ New concert</strong> to create a concert experience',
    'help.concerten.li2': 'Click a concert card to view and add photos and videos',
    'help.concerten.li3': '✎ — edit name, artist, date and story; 🗑 — delete the concert, with confirmation',
    'help.concerten.li4': 'Drag a concert card to another position to change the order — the new order is saved automatically',
    'help.concerten.li5': 'Click a photo or video to browse with ‹ › (or the arrow keys) through all media of the concert; a video only starts playing after you click the play button',
    'help.toevoegen.titel': 'Adding videos',
    'help.toevoegen.li1': '<strong>+ add track</strong> at the bottom of a wall — add a YouTube link or local file, along with artist, title, story and tag',
    'help.toevoegen.li2': '<strong>↑ Import folder</strong> — add a whole folder of local video files to a wall at once',
    'help.toevoegen.li3': '<strong>⌕ Search YouTube</strong> — search YouTube directly within Musicwall, select one or more with a click and add them all at once to the chosen wall',
    'help.toevoegen.liPlaylists': 'Choose <strong>Playlists</strong> at the top of the Search YouTube screen to search a whole playlist by artist or genre; select a playlist to see all its tracks, use <strong>Select all</strong> to select them at once and add them to the chosen wall',
    'help.toevoegen.li4': 'In Import folder and Search YouTube you first pick a group, then a wall from that group — this keeps the list manageable when you use wall groups',
    'help.afspelen.titel': 'Playing videos',
    'help.afspelen.intro': 'Click a thumbnail to play the video. The video opens fullscreen in its own window, without the YouTube interface around it.',
    'help.afspelen.li1': 'Press <strong>Escape</strong> to close the video window',
    'help.afspelen.li2': 'Hover over a thumbnail to see the play button and the edit/delete buttons',
    'help.afspelen.li3': 'A red label shows YouTube, a gold label shows a local video',
    'help.bewerken.titel': 'Editing and deleting videos',
    'help.bewerken.li1': '✎ — edit artist, title, story and tag',
    'help.bewerken.li2': '🗑 — delete a video, with confirmation',
    'help.bewerken.li3': 'Drag a video to the trash icon in the header to delete it',
    'help.bewerken.li4': 'Select multiple videos with <strong>Ctrl+click</strong> and drag them together to the trash, or delete them at once',
    'help.jukebox.titel': 'Jukebox',
    'help.jukebox.intro': 'The jukebox automatically plays a playlist of local and YouTube videos back to back. YouTube tracks need an internet connection; a track that can\'t be played (for example because the uploader disabled embedding) is removed from the playlist — the video itself still exists and can be played manually, just not through the jukebox.',
    'help.jukebox.li1': 'Select videos with <strong>Ctrl+click</strong> in a wall or concert experience — local files and YouTube videos alike',
    'help.jukebox.liAlles': 'Click the select icon in a wall header (or the <strong>☑ Select all</strong> button in a concert experience) to select all videos of that wall or concert at once; click again to deselect',
    'help.jukebox.li2': 'Click <strong>♫ Add to playlist</strong>',
    'help.jukebox.li3': 'Open the jukebox via the <strong>♫ Jukebox</strong> button in the header',
    'help.jukebox.liBibliotheekZoeken': 'From within the jukebox you can also search your entire library by artist or title, right above the playlist — click matching tracks (or use <strong>Select all</strong>) and click <strong>♫ Add to playlist</strong> to add them without closing the jukebox',
    'help.jukebox.li4': 'Use the navigation buttons to browse: first, previous, play/pause, stop, next, last. Browsing manually does not remove anything from the playlist',
    'help.jukebox.li5': 'The shuffle button (⤮) shuffles the playlist order',
    'help.jukebox.li6': 'Click the fullscreen icon at the bottom right of the video screen for fullscreen',
    'help.jukebox.li7': 'A video that finishes playing on its own is automatically removed from the playlist; playback then continues with the next track, or loops back to the first if it was the last one',
    'help.jukebox.li8': 'A message appears when the playlist is empty',
    'help.jukebox.liBeperking': 'Some official music videos (often from record labels) have embedding disabled — this is a setting made by the rights holder on YouTube itself and cannot be bypassed by Musicwall. This is more common in lists full of official music videos, such as a Top 2000 playlist; those tracks can then only be played manually, not through the jukebox',
    'help.apikey.titel': 'Setting up YouTube search',
    'help.apikey.intro': 'To search YouTube from within Musicwall you need a free YouTube API key. A screen with instructions and a link to Google appears automatically on first launch; the steps below also work if you want to set it up later.',
    'help.apikey.aanvragenTitel': 'Requesting an API key',
    'help.apikey.li1': 'Go to <strong>console.cloud.google.com</strong> and sign in with a Google account',
    'help.apikey.li2': 'Create a new project via <strong>Select a project → New project</strong>',
    'help.apikey.li3': 'Go to <strong>APIs & services → Library</strong>',
    'help.apikey.li4': 'Search for <strong>YouTube Data API v3</strong> and click <strong>Enable</strong>',
    'help.apikey.li5': 'Go to <strong>APIs & services → Credentials</strong>',
    'help.apikey.li6': 'Click <strong>Create credentials → API key</strong>',
    'help.apikey.li7': 'Copy the key that appears',
    'help.apikey.invoerenTitel': 'Entering the API key in Musicwall',
    'help.apikey.invoerLi1': 'Open the file <strong>instellingen.json</strong> in your Musicwall folder',
    'help.apikey.invoerLi2': 'Enter your key under <strong>youtubeApiKey</strong>',
    'help.apikey.invoerLi3': 'Save the file and restart Musicwall',
    'help.apikey.quota': 'Google\'s free quota allows 10,000 searches per day — more than enough for personal use.',
    'help.apikey.wijzigBtn': '🔑 Change API key',
    'apiSleutelDialoog.titel': 'Set up YouTube API key',
    'apiSleutelDialoog.titelWijzigen': 'Change YouTube API key',
    'apiSleutelDialoog.intro': 'To search YouTube from Musicwall you need a free YouTube API key. Request it once via Google and paste it below — this screen won\'t appear again once that\'s done.',
    'apiSleutelDialoog.introWijzigen': 'Update your YouTube API key here.',
    'apiSleutelDialoog.openGoogleBtn': '🔗 Open Google Cloud Console',
    'apiSleutelDialoog.sleutelLabel': 'YouTube API key',
    'apiSleutelDialoog.sleutelPlaceholder': 'Paste your API key here',
    'apiSleutelDialoog.opslaanBtn': 'Save',
    'apiSleutelDialoog.overslaanBtn': 'Set up later',
    'apiSleutelDialoog.annulerenBtn': 'Cancel',
    'apiSleutelDialoog.leegMelding': 'Enter an API key, or choose "Set up later"',
    'help.themas.titel': 'Themes',
    'help.themas.intro': 'Switch between seven available themes via the button in the top right: Default, Metal, Jukebox, Night, Raw, Nature and Light. Your choice is remembered the next time you open Musicwall.',
    'help.sneltoetsen.titel': 'Keyboard shortcuts',
    'help.sneltoetsen.li1': '<strong>Ctrl + click</strong> — select a video to drag, delete, or add to the jukebox',
    'help.sneltoetsen.li2': '<strong>Escape</strong> — clear selection, or close the video window'
  }
}


if (typeof module !== 'undefined' && module.exports) {
  module.exports = VERTALINGEN
}
